language: php
php:
    - 5.4
    - hhvm
mysql:
    database: drupal
    username: root
    encoding: utf8
before_install:
  - composer self-update
  #- pear channel-discover pear.drush.org
install:
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
before_script:
    - drush dl --yes drupal
    - cd drupal-*
    - drush si standard --db-url=mysql://root:@localhost/drupal --yes
    - drush en --yes simpletest
    - drush cc all
    - drush runserver --server=builtin 8080 &
    - sleep 4
    - drush vset --yes simpletest_verbose FALSE
script: drush test-run Syslog --xml --uri=http://127.0.0.1:8080
matrix:
    allow_failures:
        - php: hhvm
