; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.32-dev"

; Modules
projects[apachesolr][version] = "1.7"

projects[ctools][version] = "1.4"

projects[facetapi][version] = "1.5"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tests][download][type] = ""
projects[tests][download][url] = ""
projects[tests][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[psr_0_test][download][type] = ""
projects[psr_0_test][download][url] = ""
projects[psr_0_test][type] = "module"

